export const homeStyles = {
    homeBox: {
        backgroundImage: 'url(src/assets/images/cooking1.webp)',
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        height: '80vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'black',
        textAlign: 'center',
        px: 3,
    },
    homeContainer: {
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        color: 'white',
        textAlign: 'center',
        borderRadius: 5,
        p: 4,
        maxWidth: '600px',
        mx: 'auto',
    },
    homeAction: {
        backgroundColor: 'primary.main',
        color: 'white',
        py: 6,
        textAlign: 'center',
    },
    featuredCard: {
        textAlign: 'center',
        p: 3,
        boxShadow: 3,
    },
    loggedinButton: {
        backgroundColor: '#AF1F01',
        color: 'white',
        py: 2,
        px: 4,
        borderRadius: 2,
        '&:hover': {
            backgroundColor: '#3D0A00',
        },
    },
    secondaryLoggedinButton: {
        backgroundColor: '#576416',
        color: 'white',
        py: 2,
        px: 4,
        mt: 2,
        borderRadius: 2,
        '&:hover': {
            backgroundColor: '#2C320B',
        },
    },
};
